### ISSUE TITLE
Credit to Michael Jackson?

### ISSUE THREAD

**Issue by cht8687** [so-classic/react-classic-calculator#1]
I see the initial code is taken from his codepen, should we include that in the Readme?

**Comment by stevemao** [comment]
PR welcome

**Comment by cht8687** [comment]
https://github.com/stevemao/react-classic-calculator/pull/2

**Comment by stevemao** [comment]
Thanks for your contribution. You are now promoted to be a collaborator :)

**Comment by cht8687** [comment]
what about we create a new org named so-classic and we implement all classic project under that name? 😄 .. https://github.com/so-classic

**Comment by cht8687** [comment]
maybe later implement,  angular-classic-calculator, vue-classic-calculator...bla,bla,bla, anything that is classic... ✨
